# Generated by Django 5.1.7 on 2025-03-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_user_expense_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user_expense_id',
        ),
    ]
