# Generated by Django 5.1.7 on 2025-03-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('food', 'Food'), ('shopping', 'Shopping'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
