# Generated by Django 5.1.7 on 2025-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('food', 'Food'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
