# Generated by Django 5.1.7 on 2025-03-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='budget_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
